import AppKit
import ImageIO
import UniformTypeIdentifiers
import Vision

/// Watches the general pasteboard and feeds new copies to clipboard history.
///
/// Polling, because there is no push API — `NSPasteboard` exposes `changeCount` and
/// nothing that notifies. 200ms is CLAUDE.md's figure: far below the time between
/// copying something and opening the launcher to find it.
@MainActor
final class ClipboardWatcher {
    static let pollInterval: Duration = .milliseconds(200)

    /// Every marker nspasteboard.org defines, plus the one proprietary type it documents.
    /// CLAUDE.md names only the first two; the spec has four. Content carrying any of them
    /// is never read, let alone stored — and since history persists to disk, that matters
    /// for `ConcealedType` in particular, whose spec says to "avoid recording it to a file".
    nonisolated static let skipMarkers: Set<String> = [
        "org.nspasteboard.TransientType",  // "should not be recorded or displayed"
        "org.nspasteboard.ConcealedType",  // passwords; "avoid recording it to a file"
        "org.nspasteboard.AutoGeneratedType",  // "the user had no intention to Copy"
        "com.agilebits.onepassword",  // 1Password's marker, which predates the standard ones
    ]

    private let sink: ClipSink
    /// The general pasteboard in the app. A parameter so a harness can drive the real
    /// panel's copy actions against a private pasteboard, never the user's clipboard.
    private let pasteboard: NSPasteboard
    private var lastSeen: Int
    /// The `changeCount` of blindspot's own most recent write, so it is not re-ingested.
    private var ownWrite: Int?
    private var task: Task<Void, Never>?
    private struct PendingClip: Sendable {
        let data: Data
        let image: Bool
        let readingText: Bool
    }
    private var pending: [PendingClip] = []
    private var ingestion: Task<Void, Never>?
    private var pendingBytes = 0
    private var clearing = false
    /// Whether to record images at all, and whether to read the text in one. Both are
    /// settings, and both are read here rather than in Rust because the pasteboard and
    /// Vision are AppKit's.
    var recordsImages = true
    var readsImageText = true

    init(sink: ClipSink, pasteboard: NSPasteboard = .general) {
        self.sink = sink
        self.pasteboard = pasteboard
        // A baseline, not a read: whatever was copied before launch is ignored on purpose.
        // `changeCount` exposes no contents, so it stays clear of the access alert
        // `NSPasteboard.h` documents — an alert that, on macOS 26.4, did not fire even for
        // real content reads. See CLAUDE.md; a future macOS may start enforcing it.
        lastSeen = pasteboard.changeCount
    }

    func start() {
        guard task == nil, !clearing else { return }
        task = Task { @MainActor [weak self] in
            while !Task.isCancelled {
                guard let self else { return }
                self.poll()
                try? await Task.sleep(for: ClipboardWatcher.pollInterval)
            }
        }
    }

    func stop() {
        task?.cancel()
        task = nil
        ingestion?.cancel()
        pending.removeAll()
        pendingBytes = 0
    }

    func prepareToClear() async {
        clearing = true
        stop()
        await ingestion?.value
        lastSeen = pasteboard.changeCount
    }

    func finishClearing() {
        lastSeen = pasteboard.changeCount
        clearing = false
    }

    /// Puts something on the pasteboard without it coming straight back into history.
    ///
    /// Re-pasting a clip is recorded by bumping it through `bs_activate` instead. Letting
    /// the watcher re-read it would duplicate images outright: an image goes back on the
    /// pasteboard as TIFF, re-encodes to different PNG bytes, and hashes to a new id.
    /// Puts something on the pasteboard, and lets the poller record it like any other copy.
    ///
    /// Which is the point: pressing ↩ on a figure, a path, a pid or the model's answer *is*
    /// copying something, and a history that omits everything you deliberately copied out
    /// of the launcher is a history with a hole in it. Re-copying something already in
    /// history dedups to a bump rather than a duplicate, so this is safe even then.
    func copy(_ body: (NSPasteboard) -> Void) {
        pasteboard.clearContents()
        body(pasteboard)
    }

    /// As [`copy`], but the poller skips what this writes.
    ///
    /// One case needs it: putting an *image* clip back. `writeObjects` offers several
    /// representations and the bytes are not the PNG that was stored, so the content hash
    /// differs and history would gain a near-duplicate of the thing you just pasted. A clip
    /// is already in history by definition — `bs_activate` bumps it — so there is nothing
    /// to record.
    func writeOwn(_ body: (NSPasteboard) -> Void) {
        pasteboard.clearContents()
        body(pasteboard)
        ownWrite = pasteboard.changeCount
    }

    /// Pure, so it can be tested without reading a real pasteboard — and so without the
    /// test itself triggering the access alert.
    nonisolated static func shouldSkip(types: [String]) -> Bool {
        types.contains(where: skipMarkers.contains)
    }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastSeen else { return }
        lastSeen = count
        guard count != ownWrite else { return }

        // Types first. A marked copy is refused here, before its content is ever read into
        // this process.
        let types = pasteboard.types?.map(\.rawValue) ?? []
        guard !Self.shouldSkip(types: types) else { return }

        let image = recordsImages
            ? pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff)
            : nil
        if let data = image {
            enqueue(PendingClip(data: data, image: true, readingText: readsImageText))
        } else if let text = pasteboard.string(forType: .string) {
            enqueue(PendingClip(data: Data(text.utf8), image: false, readingText: false))
        }
    }

    private func enqueue(_ clip: PendingClip) {
        guard clip.data.count <= (clip.image ? 25 * 1024 * 1024 : 1024 * 1024) else { return }
        while !pending.isEmpty && (pending.count >= 16 || pendingBytes + clip.data.count > 32 * 1024 * 1024) {
            pendingBytes -= pending.removeFirst().data.count
        }
        pending.append(clip)
        pendingBytes += clip.data.count
        drain()
    }

    private func drain() {
        guard ingestion == nil, !pending.isEmpty else { return }
        let clip = pending.removeFirst()
        pendingBytes -= clip.data.count
        let sink = self.sink
        ingestion = Task { [weak self] in
            let worker = Task.detached(priority: .utility) {
                guard !Task.isCancelled else { return }
                if clip.image {
                    guard let encoded = ImageClip.encode(clip.data, readingText: clip.readingText),
                          !Task.isCancelled else { return }
                    sink.add(image: true, content: encoded.png, thumbnail: encoded.thumbnail,
                             text: Data(encoded.text.utf8), width: encoded.width, height: encoded.height)
                } else {
                    sink.add(image: false, content: clip.data)
                }
            }
            await withTaskCancellationHandler { await worker.value } onCancel: { worker.cancel() }
            guard let self else { return }
            self.ingestion = nil
            self.drain()
        }
    }
}

/// Off-main image encoding. ImageIO rather than `NSImage`, because ImageIO is documented
/// thread-safe and `NSImage` is not.
enum ImageClip {
    struct Encoded: Sendable {
        let png: Data
        let thumbnail: Data
        /// Text recognised in the image, top line first; empty if there is none.
        let text: String
        let width: Int
        let height: Int
    }

    /// 96pt at 2x. Stored per clip so a result row never decodes a full screenshot.
    static let thumbnailPixels = 192

    /// `readingText` off skips the Vision pass — about 99ms on a full-screen capture —
    /// and the clip is then named by its size rather than by what it says.
    static func encode(_ data: Data, readingText: Bool = true) -> Encoded? {
        guard data.count <= 25 * 1024 * 1024,
              let source = CGImageSourceCreateWithData(data as CFData, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
              let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue,
              width > 0, height > 0, width <= 50_000_000 / height,
              let image = CGImageSourceCreateImageAtIndex(source, 0, nil)
        else { return nil }

        // Already a PNG: keep the original bytes rather than paying to re-encode them.
        let isPNG = (CGImageSourceGetType(source) as String?) == UTType.png.identifier
        guard let png = isPNG ? data : pngData(image) else { return nil }

        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: thumbnailPixels,
        ]
        let thumbnail =
            CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary)
            .flatMap(pngData) ?? Data()

        return Encoded(
            png: png, thumbnail: thumbnail,
            text: readingText ? recognizeText(image) : "",
            width: image.width, height: image.height)
    }

    /// The text in an image, in reading order, via Vision's on-device recogniser.
    ///
    /// `.accurate`, not `.fast`: on a 3024 × 1964 screenshot, fast took 16ms and returned
    /// `errorlE05991` and dropped French accents; accurate took 99ms warm and returned
    /// `error[E0599]` and "vérifiez" intact. The whole decode-encode-recognise step measured
    /// 367ms on a cold first run. It happens once per copied image, off the main thread,
    /// before the clip is stored — slower than a keystroke, faster than copy-then-open.
    /// English and French because this is a bilingual machine; detection picks between them.
    ///
    /// On-device text recognition, not an AI feature: deterministic, no network, and the
    /// same recogniser behind Live Text. Chosen deliberately against CLAUDE.md's "No AI".
    private static func recognizeText(_ image: CGImage) -> String {
        let request = VNRecognizeTextRequest()
        request.recognitionLevel = .accurate
        request.recognitionLanguages = ["en-US", "fr-FR"]
        request.automaticallyDetectsLanguage = true
        request.usesLanguageCorrection = true
        guard (try? VNImageRequestHandler(cgImage: image).perform([request])) != nil else {
            return ""
        }
        // Vision does not promise reading order, and the first line becomes the title, so
        // sort top to bottom, then left to right. Its coordinates put y = 0 at the bottom.
        let lines = (request.results ?? []).sorted { a, b in
            let ay = a.boundingBox.midY, by = b.boundingBox.midY
            if abs(ay - by) > 0.01 { return ay > by }
            return a.boundingBox.minX < b.boundingBox.minX
        }
        return lines.compactMap { $0.topCandidates(1).first?.string }.joined(separator: "\n")
    }

    private static func pngData(_ image: CGImage) -> Data? {
        let out = NSMutableData()
        guard
            let destination = CGImageDestinationCreateWithData(
                out, UTType.png.identifier as CFString, 1, nil)
        else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return out as Data
    }
}
