import AppKit
@preconcurrency import ApplicationServices
import Carbon

enum ContextValue<Value: Sendable>: Sendable {
    case available(Value)
    case unavailable
    case permissionRequired
    case failed
}

struct LauncherContext: Sendable {
    let applicationID: String?
    let processID: pid_t
    let selectedText: ContextValue<String>
    let windowTitle: ContextValue<String>
    let documentURL: ContextValue<URL>
    var clipboardText: ContextValue<String> = .unavailable
    var pageText: ContextValue<String> = .unavailable
    var workingDirectory: ContextValue<URL> = .unavailable
    var finderDirectory: ContextValue<URL> = .unavailable

    var textForAI: String? {
        guard case let .available(text) = selectedText else { return nil }
        return text
    }

    static func capture(applicationID: String?, processID: pid_t, requestAccess: Bool = false, request: String = "") async -> LauncherContext {
        let copied = request.lowercased().contains("copied") || request.lowercased().contains("clipboard")
        if requestAccess && !copied {
            _ = await MainActor.run {
                AXIsProcessTrustedWithOptions([kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true] as CFDictionary)
            }
        }
        let clipboard: ContextValue<String> = requestAccess && copied ? await MainActor.run {
            let board = NSPasteboard.general
            let concealed: Set<String> = ["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
            guard !(board.types ?? []).contains(where: { concealed.contains($0.rawValue) }),
                  let value = board.string(forType: .string), !value.isEmpty, value.utf8.count <= 16_000 else { return .unavailable }
            return .available(value)
        } : .unavailable
        let worker = Task.detached(priority: .userInitiated) {
            let window = focusedWindow(processID: processID)
            var snapshot = LauncherContext(applicationID: applicationID, processID: processID,
                selectedText: selectedText(processID: processID), windowTitle: window.0, documentURL: window.1)
            snapshot.clipboardText = clipboard
            if let applicationID, !copied {
                let extra = automation(applicationID, requestAccess: requestAccess)
                var document = window.1
                if case let .available(values) = extra {
                    if let selection = values.selection?.first, let url = URL(string: selection), url.isFileURL {
                        document = .available(url)
                    } else if let value = values.url, let url = URL(string: value), ["http", "https"].contains(url.scheme ?? "") {
                        document = .available(url)
                    }
                    if let value = values.directory, let url = URL(string: value), url.isFileURL { snapshot.finderDirectory = .available(url) }
                    if let tty = values.tty, tty.hasPrefix("/dev/tty"), tty.dropFirst(5).allSatisfy({ $0.isLetter || $0.isNumber }) {
                        if let data = try? NativeJob.runSync(executable: URL(fileURLWithPath: "/bin/ps"), arguments: ["-t", String(tty.dropFirst(5)), "-o", "pid=,pgid=,tpgid="], timeout: 2) {
                            let rows = String(decoding: data, as: UTF8.self).split(separator: "\n").map { $0.split(whereSeparator: { $0.isWhitespace }).compactMap { UInt64($0) } }
                            if let row = rows.first(where: { $0.count == 3 && $0[0] == $0[2] }),
                               let details = try? await NativeProcessBridge.inspect(pid: row[0], started: 0), let path = details.workingDirectory {
                                snapshot.workingDirectory = .available(URL(fileURLWithPath: path))
                            }
                        }
                    }
                }
                snapshot = LauncherContext(applicationID: applicationID, processID: processID,
                    selectedText: snapshot.selectedText, windowTitle: snapshot.windowTitle, documentURL: document,
                    clipboardText: clipboard, pageText: .unavailable, workingDirectory: snapshot.workingDirectory, finderDirectory: snapshot.finderDirectory)
                if requestAccess && request.lowercased().contains("page") && ["com.apple.Safari", "com.google.Chrome", "com.brave.Browser", "com.microsoft.edgemac"].contains(applicationID) {
                    snapshot.pageText = browserText(processID: processID)
                }
            }
            return snapshot
        }
        return await withTaskCancellationHandler { await worker.value } onCancel: { worker.cancel() }
    }

    func reference(for request: String) -> String? {
        let request = request.lowercased()
        if request.contains("copied") || request.contains("clipboard") {
            if case let .available(text) = clipboardText { return text }
            return nil
        }
        if request.contains("page") {
            if case let .available(text) = pageText { return text }
            return nil
        }
        return textForAI
    }

    var projectDirectory: URL? {
        if case let .available(url) = workingDirectory { return url }
        if case let .available(url) = finderDirectory { return url }
        if case let .available(url) = documentURL, url.isFileURL { return url.deletingLastPathComponent() }
        return nil
    }

    private struct AutomationValues: Decodable, Sendable {
        var selection: [String]?
        var directory: String?
        var url: String?
        var tty: String?
    }

    private static func automation(_ applicationID: String, requestAccess: Bool) -> ContextValue<AutomationValues> {
        guard !Task.isCancelled else { return .unavailable }
        let body: String
        switch applicationID {
        case "com.apple.finder": body = "const a=Application('Finder'); out.selection=a.selection().slice(0,32).map(x=>x.url()); try {out.directory=a.insertionLocation().url()} catch(e) {}"
        case "com.apple.Safari": body = "const a=Application('Safari'); if(a.windows.length) out.url=a.windows[0].currentTab.url();"
        case "com.google.Chrome", "com.brave.Browser", "com.microsoft.edgemac":
            let app = applicationID == "com.google.Chrome" ? "Google Chrome" : (applicationID == "com.brave.Browser" ? "Brave Browser" : "Microsoft Edge")
            body = "const a=Application('" + app + "'); if(a.windows.length) out.url=a.windows[0].activeTab.url();"
        case "com.apple.Terminal": body = "const a=Application('Terminal'); if(a.windows.length) out.tty=a.windows[0].selectedTab.tty();"
        case "com.googlecode.iterm2": body = "const a=Application('iTerm'); if(a.currentWindow()) out.tty=a.currentWindow().currentTab().currentSession().tty();"
        default: return .unavailable
        }
        let descriptor = NSAppleEventDescriptor(bundleIdentifier: applicationID)
        guard let target = descriptor.aeDesc else { return .unavailable }
        guard AEDeterminePermissionToAutomateTarget(target, typeWildCard, typeWildCard, requestAccess) == noErr else { return .permissionRequired }
        guard !Task.isCancelled else { return .unavailable }
        do {
            let data = try NativeJob.runSync(executable: URL(fileURLWithPath: "/usr/bin/osascript"),
                arguments: ["-l", "JavaScript", "-e", "let out={}; try {" + body + "} catch(e) {} JSON.stringify(out);"], timeout: 2)
            return .available(try JSONDecoder().decode(AutomationValues.self, from: data))
        } catch { return Task.isCancelled ? .unavailable : .failed }
    }

    private static func browserText(processID: pid_t) -> ContextValue<String> {
        guard AXIsProcessTrusted() else { return .permissionRequired }
        let app = AXUIElementCreateApplication(processID)
        AXUIElementSetMessagingTimeout(app, 0.1)
        var window: CFTypeRef?
        guard AXUIElementCopyAttributeValue(app, kAXFocusedWindowAttribute as CFString, &window) == .success,
              let window, CFGetTypeID(window) == AXUIElementGetTypeID() else { return .unavailable }
        var queue: [(AXUIElement, Bool)] = [(unsafeDowncast(window, to: AXUIElement.self), false)]
        var text = ""
        var cursor = 0
        let deadline = ContinuousClock.now + .seconds(2)
        while cursor < queue.count && cursor < 400 && text.utf8.count < 16_000 {
            guard !Task.isCancelled, ContinuousClock.now < deadline else { return .unavailable }
            let (element, inside) = queue[cursor]; cursor += 1
            AXUIElementSetMessagingTimeout(element, 0.05)
            var role: CFTypeRef?
            AXUIElementCopyAttributeValue(element, kAXRoleAttribute as CFString, &role)
            let roleName = role as? String ?? ""
            let web = inside || roleName == "AXWebArea"
            if web && roleName == "AXStaticText" {
                var value: CFTypeRef?
                AXUIElementCopyAttributeValue(element, kAXValueAttribute as CFString, &value)
                if let value = value as? String { text += String(value.prefix(16_000)) + "\n" }
            }
            if queue.count < 400 && roleName != "AXTextField" && roleName != "AXTextArea" {
                var children: CFTypeRef?
                AXUIElementCopyAttributeValue(element, kAXChildrenAttribute as CFString, &children)
                if let children = children as? [AXUIElement] { queue += children.prefix(400 - queue.count).map { ($0, web) } }
            }
        }
        return text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? .unavailable : .available(String(decoding: text.utf8.prefix(16_000), as: UTF8.self))
    }

    var hasTextObject: Bool {
        if textForAI != nil { return true }
        if case let .available(url) = documentURL { return url.isFileURL && FileText.supports(url) }
        return false
    }

    static func isTextCommand(_ text: String) -> Bool {
        let text = text.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        return ["rewrite", "summarize", "explain", "translate"].contains {
            text == $0 || text.hasPrefix($0 + " ")
        }
    }

    private static func focusedWindow(processID: pid_t) -> (ContextValue<String>, ContextValue<URL>) {
        guard !Task.isCancelled else { return (.unavailable, .unavailable) }
        guard AXIsProcessTrusted() else { return (.permissionRequired, .permissionRequired) }
        let app = AXUIElementCreateApplication(processID)
        AXUIElementSetMessagingTimeout(app, 0.15)
        var value: CFTypeRef?
        let status = AXUIElementCopyAttributeValue(app, kAXFocusedWindowAttribute as CFString, &value)
        guard status == .success, let value, CFGetTypeID(value) == AXUIElementGetTypeID() else {
            return status == .cannotComplete ? (.failed, .failed) : (.unavailable, .unavailable)
        }
        let window = unsafeDowncast(value, to: AXUIElement.self)
        AXUIElementSetMessagingTimeout(window, 0.15)
        guard !Task.isCancelled else { return (.unavailable, .unavailable) }
        var title: CFTypeRef?
        AXUIElementCopyAttributeValue(window, kAXTitleAttribute as CFString, &title)
        var document: CFTypeRef?
        AXUIElementCopyAttributeValue(window, kAXDocumentAttribute as CFString, &document)
        let name = (title as? String).flatMap { $0.utf8.count <= 1024 ? $0 : nil }
        let url = (document as? URL) ?? (document as? String).flatMap(URL.init(string:))
        let safeURL = url.flatMap { ["file", "http", "https"].contains($0.scheme?.lowercased() ?? "") ? $0 : nil }
        return (name.map(ContextValue.available) ?? .unavailable, safeURL.map(ContextValue.available) ?? .unavailable)
    }

    private static func selectedText(processID: pid_t) -> ContextValue<String> {
        guard !Task.isCancelled else { return .unavailable }
        guard AXIsProcessTrusted() else { return .permissionRequired }
        let app = AXUIElementCreateApplication(processID)
        AXUIElementSetMessagingTimeout(app, 0.15)
        var focused: CFTypeRef?
        let focusedStatus = AXUIElementCopyAttributeValue(app, kAXFocusedUIElementAttribute as CFString, &focused)
        guard focusedStatus == .success, let focused,
              CFGetTypeID(focused) == AXUIElementGetTypeID() else {
            return focusedStatus == .cannotComplete ? .failed : .unavailable
        }
        guard !Task.isCancelled else { return .unavailable }
        let element = unsafeDowncast(focused, to: AXUIElement.self)
        AXUIElementSetMessagingTimeout(element, 0.15)
        var role: CFTypeRef?
        AXUIElementCopyAttributeValue(element, kAXSubroleAttribute as CFString, &role)
        guard (role as? String) != "AXSecureTextField" else { return .unavailable }
        var selected: CFTypeRef?
        let status = AXUIElementCopyAttributeValue(element, kAXSelectedTextAttribute as CFString, &selected)
        guard status == .success else { return status == .cannotComplete ? .failed : .unavailable }
        guard let text = selected as? String, !text.isEmpty, text.utf8.count <= 16_384 else { return .unavailable }
        return Task.isCancelled ? .unavailable : .available(text)
    }
}
