#!/usr/bin/env bash
# PreToolUse on file writes. Blocks edits to secrets and generated artifacts.
set -uo pipefail

input=$(cat)
file=$(printf '%s' "$input" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("tool_input",{}).get("file_path",""))' 2>/dev/null)

[[ -n "$file" ]] || exit 0

block() { echo "BLOCKED: $1" >&2; exit 2; }

case "$file" in
  *.env|*.env.*|*/secrets/*|*id_rsa*|*.p12|*.mobileprovision)
    block "$file holds credentials or signing material." ;;
  */target/*|*/.build/*|*/DerivedData/*)
    block "$file is a build artifact. Change the source, not the output." ;;
  */include/blindspot.h)
    block "blindspot.h is generated by cbindgen. Edit core/src/ffi.rs and regenerate." ;;
esac

exit 0
