//! Calendar arithmetic for UTC timestamps, with no date crate.
//!
//! Two callers need it: Spotlight's usage dates arrive as text (`2026-07-06 04:00:00 +0000`)
//! and must become epochs to decay, and the epoch tool turns `@1757548800` back into a date.
//! Howard Hinnant's days-from-civil algorithm does both exactly for the proleptic Gregorian
//! calendar in a dozen lines; `chrono` would be a dependency for one conversion. Local time is
//! deliberately absent — it needs the time-zone database, and the Swift side already has it.

const SECS_PER_DAY: i64 = 86_400;

/// Days since 1970-01-01 for a Gregorian date.
fn days_from_civil(year: i64, month: u32, day: u32) -> i64 {
    let year = if month <= 2 { year - 1 } else { year };
    let era = (if year >= 0 { year } else { year - 399 }) / 400;
    let yoe = year - era * 400;
    let mp = i64::from((month + 9) % 12);
    let doy = (153 * mp + 2) / 5 + i64::from(day) - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    era * 146_097 + doe - 719_468
}

/// The Gregorian date for a count of days since 1970-01-01.
fn civil_from_days(days: i64) -> (i64, u32, u32) {
    let z = days + 719_468;
    let era = (if z >= 0 { z } else { z - 146_096 }) / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let month = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    let year = yoe + era * 400 + i64::from(month <= 2);
    (year, month, day)
}

/// `2026-07-06 04:00:00 +0000` — the format `mdfind -attr` prints — to Unix seconds.
/// `None` for anything else, including dates before 1970.
pub fn parse_spotlight(text: &str) -> Option<u64> {
    let text = text.trim();
    let (date, rest) = text.split_once(' ')?;
    let (time, offset) = rest.split_once(' ')?;

    let mut d = date.split('-');
    let (year, month, day) = (
        d.next()?.parse().ok()?,
        d.next()?.parse().ok()?,
        d.next()?.parse().ok()?,
    );
    let mut t = time.split(':');
    let (h, m, s): (i64, i64, i64) = (
        t.next()?.parse().ok()?,
        t.next()?.parse().ok()?,
        t.next()?.parse().ok()?,
    );
    if d.next().is_some()
        || t.next().is_some()
        || !(1..=12).contains(&month)
        || !(1..=31).contains(&day)
    {
        return None;
    }

    // `+0000` in practice, but honour whatever offset is written rather than assume it.
    let sign = match offset.chars().next()? {
        '+' => 1,
        '-' => -1,
        _ => return None,
    };
    let digits = offset.get(1..)?;
    if digits.len() != 4 {
        return None;
    }
    let off_h: i64 = digits.get(..2)?.parse().ok()?;
    let off_m: i64 = digits.get(2..)?.parse().ok()?;
    let offset_secs = sign * (off_h * 3_600 + off_m * 60);

    let secs =
        days_from_civil(year, month, day) * SECS_PER_DAY + h * 3_600 + m * 60 + s - offset_secs;
    u64::try_from(secs).ok()
}

/// `2025-09-11 00:00:00`, in UTC.
pub fn format_utc(epoch: u64) -> String {
    let (year, month, day, h, m, s) = split(epoch);
    format!("{year:04}-{month:02}-{day:02} {h:02}:{m:02}:{s:02}")
}

/// `2025-09-11T00:00:00Z`, ISO 8601 in UTC.
pub fn format_iso(epoch: u64) -> String {
    let (year, month, day, h, m, s) = split(epoch);
    format!("{year:04}-{month:02}-{day:02}T{h:02}:{m:02}:{s:02}Z")
}

fn split(epoch: u64) -> (i64, u32, u32, u64, u64, u64) {
    let days = (epoch / SECS_PER_DAY as u64) as i64;
    let rem = epoch % SECS_PER_DAY as u64;
    let (year, month, day) = civil_from_days(days);
    (year, month, day, rem / 3_600, rem % 3_600 / 60, rem % 60)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Expected values generated by Python's `datetime`, not by this module.
    const VECTORS: &[(&str, u64)] = &[
        ("1970-01-01 00:00:00", 0),
        ("2000-02-29 12:34:56", 951_827_696),
        ("2024-02-29 23:59:59", 1_709_251_199),
        ("2025-09-11 00:00:00", 1_757_548_800),
        ("2026-07-06 04:00:00", 1_783_310_400),
        ("2100-03-01 00:00:00", 4_107_542_400),
        ("2038-01-19 03:14:08", 2_147_483_648),
    ];

    #[test]
    fn spotlight_dates_parse_to_the_right_epoch() {
        for (text, epoch) in VECTORS {
            assert_eq!(
                parse_spotlight(&format!("{text} +0000")),
                Some(*epoch),
                "{text}"
            );
        }
    }

    #[test]
    fn formatting_is_the_exact_inverse() {
        for (text, epoch) in VECTORS {
            assert_eq!(format_utc(*epoch), *text);
            assert_eq!(format_iso(*epoch), format!("{}Z", text.replace(' ', "T")));
        }
    }

    #[test]
    fn offsets_are_honoured_not_assumed() {
        // Midnight in UTC-4 is 04:00 UTC — exactly how Spotlight stores a day in Montreal.
        assert_eq!(
            parse_spotlight("2026-07-06 00:00:00 -0400"),
            parse_spotlight("2026-07-06 04:00:00 +0000")
        );
    }

    #[test]
    fn garbage_is_refused() {
        for bad in [
            "",
            "2026-07-06",
            "2026-13-01 00:00:00 +0000",
            "2026-07-06 04:00:00",
            "2026-07-06 04:00:00 +00",
            "1969-12-31 23:59:59 +0000",
            "(null)",
        ] {
            assert_eq!(parse_spotlight(bad), None, "{bad:?}");
        }
    }
}
