#ifndef BLINDSPOT_H
#define BLINDSPOT_H

/* Generated by cbindgen. Edit core/src/ffi.rs and run `make header`; do not edit this file. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Most clips kept by default. Oldest go first. Settable — see [`Clips::keep`] — unlike
 * the byte caps below, which are a disk-safety invariant rather than a preference.
 */
#define DEFAULT_KEEP 200

#define MAX_BODY_BYTES 65536

#define MAX_BATCH 256

#define MAX_CANDIDATES 10000

/**
 * Newer vectors searched exactly at query time before a shard rebuild is worth its cost.
 */
#define MAX_DELTA 2048

/**
 * A [`BsResult`] that is an application bundle.
 */
#define BS_KIND_APP 0

/**
 * A [`BsResult`] that is a file found through Spotlight.
 */
#define BS_KIND_FILE 1

/**
 * A [`BsResult`] that is a calculator answer. Its `path` is empty — there is nothing to
 * open — and `name` is the formatted result, which Swift copies on Enter.
 */
#define BS_KIND_CALC 2

/**
 * A [`BsResult`] that is a text clip from clipboard history.
 */
#define BS_KIND_CLIP_TEXT 3

/**
 * A [`BsResult`] that is an image clip from clipboard history.
 */
#define BS_KIND_CLIP_IMAGE 4

/**
 * A [`BsResult`] from an SRE tool — an epoch, a unit conversion, an encoding. Like
 * [`BS_KIND_CALC`], no path, and Enter copies `name`; `detail` says which form it is.
 */
#define BS_KIND_TOOL 5

/**
 * A [`BsResult`] that is the agent's "ask the model" row. Enter submits the request.
 */
#define BS_KIND_AGENT_PROMPT 7

/**
 * A [`BsResult`] that is a command the agent proposes. Enter runs the whole plan.
 */
#define BS_KIND_AGENT_STEP 8

/**
 * A [`BsResult`] that is a command blindspot refuses to run, or an error. `detail` says why.
 */
#define BS_KIND_AGENT_BLOCKED 9

/**
 * A [`BsResult`] that is a command that ran and succeeded; `detail` is its last output line.
 */
#define BS_KIND_AGENT_OK 10

/**
 * A [`BsResult`] that is a command that ran and failed.
 */
#define BS_KIND_AGENT_FAILED 11

/**
 * A [`BsResult`] that is prose: the model answered a question. `name` is the whole answer,
 * which the shell wraps over as many lines as it needs. Enter copies it.
 */
#define BS_KIND_AGENT_ANSWER 12

/**
 * A [`BsResult`] that is the command running right now. Enter leaves it running — a server
 * never exits, and waiting for it to is not a useful answer — and Esc stops it.
 */
#define BS_KIND_AGENT_RUNNING 14

/**
 * A [`BsResult`] that is a past request from the agent's history. Enter puts it back in the
 * field, ready to ask again; `detail` says what became of it.
 */
#define BS_KIND_AGENT_PAST 15

/**
 * A [`BsResult`] that is one model in the picker. Enter on it makes it the model to ask, and
 * `id` is its index for [`bs_agent_choose`].
 */
#define BS_KIND_AGENT_MODEL 13

/**
 * A [`BsResult`] that is a process listening on the port you asked about. `id` is its
 * pid, `path` its executable, and `detail` the pid and address it is bound to. Enter
 * copies the pid; ⌃↩ asks it to stop.
 */
#define BS_KIND_PORT 16

/**
 * A registered command whose path carries the query to complete.
 */
#define BS_KIND_COMMAND 17

/**
 * A setting whose path carries its schema key.
 */
#define BS_KIND_SETTING 18

/**
 * A `:link` / `:snippet` command that saves or removes a shortcut when run; `path` is the command.
 */
#define BS_KIND_SHORTCUT 19

/**
 * A saved quick link; `path` is the URL, or the template when no search text was typed.
 */
#define BS_KIND_LINK 20

/**
 * A saved text snippet; `path` is its text.
 */
#define BS_KIND_SNIPPET 21

/**
 * A macOS system command; `path` is its identifier in [`crate::system::COMMANDS`].
 */
#define BS_KIND_SYSTEM 22

/**
 * An AI command for selected text; `path` is what to type to run it.
 */
#define BS_KIND_PROMPT 23

/**
 * A [`BsResult`] that is a section title on the welcome screen — "Suggested", "Recent
 * files". Not selectable; `name` is the title and everything else is empty.
 */
#define BS_KIND_HEADER 6

/**
 * `part` for [`bs_clip_content`]: the full text, or the full PNG.
 */
#define BS_CLIP_FULL 0

/**
 * `part` for [`bs_clip_content`]: the row thumbnail. Empty for text clips.
 */
#define BS_CLIP_THUMBNAIL 1

/**
 * A [`BsSetting`] holding `true` or `false`.
 */
#define BS_SETTING_FLAG 0

/**
 * A whole number, bounded by `min` and `max`.
 */
#define BS_SETTING_COUNT 1

/**
 * A real number, bounded by `min` and `max`.
 */
#define BS_SETTING_NUMBER 2

/**
 * Free text.
 */
#define BS_SETTING_TEXT 3

/**
 * A hotkey chord, validated by the same parser config.toml is read with.
 */
#define BS_SETTING_CHORD 4

/**
 * A list of folders, NUL-separated in `value`.
 */
#define BS_SETTING_PATHS 5

/**
 * A diagnostic. Never settable.
 */
#define BS_SETTING_READONLY 6

/**
 * Nothing set this; it is the built-in.
 */
#define BS_SOURCE_DEFAULT 0

/**
 * The user's hand-edited config.toml.
 */
#define BS_SOURCE_CONFIG 1

/**
 * The settings window.
 */
#define BS_SOURCE_OVERRIDE 2

/**
 * Carbon modifier masks from `Events.h` — *not* `NSEvent.ModifierFlags`, which use different
 * bits entirely. Verified by compiling against the SDK: `cmdKey` = 256, `shiftKey` = 512.
 */
#define CMD 256

#define SHIFT 512

#define OPTION 2048

#define CONTROL 4096

/**
 * A path list crosses the FFI NUL-separated: a macOS path may contain any byte except
 * `/` and NUL, so NUL is the only separator that cannot appear inside a member. The
 * boundary already passes pointer + length rather than C strings for the same reason.
 */
#define LIST_SEPARATOR '\u{0}'

#define MAX_ENTRIES 256

#define MAX_SNIPPET_BYTES (16 * 1024)

#define SNIPPET_PREFIX '!'

/**
 * Spotlight's usage score at or above which an app counts as recently used: one use four
 * weeks ago at the default 14-day half-life (`0.5^(28/14)`).
 */
#define RECENT_SCORE 0.25

/**
 * Opaque to C. Swift only ever holds a `BsHandle *`.
 */
typedef struct BsHandle BsHandle;

typedef struct Hotkey Hotkey;

/**
 * One ranked match.
 *
 * `name` and `path` are pointer + length, not NUL-terminated: a bundle path is bytes
 * on macOS, not necessarily valid UTF-8, and a length keeps that honest. Swift reads
 * them with `String(decoding:as:)` over an `UnsafeRawBufferPointer`.
 *
 * `path` is in the struct because Swift needs it twice — once for
 * `NSWorkspace.icon(forFile:)` and once to launch — and re-deriving it from `id` would
 * mean a second FFI call per row per keystroke.
 */
typedef struct {
  uint64_t id;
  uint32_t process_pid;
  uint16_t network_port;
  const uint8_t *name;
  size_t name_len;
  const uint8_t *path;
  size_t path_len;
  uint32_t score;
  /**
   * One of the `BS_KIND_*` constants. Swift needs it to decide what Enter does.
   */
  uint8_t kind;
  /**
   * Unix seconds a clip was last copied, so Swift can show "2 min ago" with its own
   * localized formatter. Zero for anything that is not a clip.
   */
  uint64_t timestamp;
  /**
   * Pixel size of an image clip, zero otherwise. Swift compares it against the
   * attached displays to call a full-screen capture a screenshot.
   */
  uint32_t width;
  uint32_t height;
  /**
   * A tool row's subtitle — "binary", "ISO 8601", "decoded". NULL for everything else.
   * For an epoch, `timestamp` carries the instant too, because only Swift knows the
   * local time zone to render it in.
   */
  const uint8_t *detail;
  size_t detail_len;
  /**
   * Which characters of `name` the query matched, as offsets into its `char`s —
   * Unicode scalars, not bytes and not UTF-16 units. The shell sets them in the accent,
   * which is the only thing colour does in a results list besides mark the selection.
   *
   * NULL for every row nothing was typed at: a calculated value, an agent row, a
   * section title, and every row of a browse mode with an empty query.
   */
  const uint32_t *highlights;
  size_t highlights_len;
} BsResult;

/**
 * A pointer and a length, so one query is one struct rather than a Swift-side array
 * copy per keystroke. Must be passed to [`bs_free_results`] on every path.
 */
typedef struct {
  BsResult *items;
  size_t len;
  /**
   * True while a file search for this query is still running, meaning more results
   * may follow. Swift polls until it goes false. Always false for a query with no
   * `?` prefix, because nothing asynchronous was started.
   */
  bool pending;
} BsResults;

/**
 * Bytes owned by Rust. Must be passed to [`bs_free_blob`].
 */
typedef struct {
  const uint8_t *data;
  size_t len;
} BsBlob;

/**
 * A clip handed from Swift to Rust. Every pointer only has to live for the call:
 * [`bs_clip_add`] copies whatever it keeps before returning.
 */
typedef struct {
  /**
   * [`BS_KIND_CLIP_TEXT`] or [`BS_KIND_CLIP_IMAGE`].
   */
  uint8_t kind;
  /**
   * UTF-8 text, or PNG bytes.
   */
  const uint8_t *content;
  size_t content_len;
  /**
   * A small PNG for the row. May be NULL for text.
   */
  const uint8_t *thumbnail;
  size_t thumbnail_len;
  /**
   * For images, UTF-8 text recognised in the image, which becomes its name and makes it
   * searchable. May be NULL. Ignored for text clips.
   */
  const uint8_t *text;
  size_t text_len;
  uint32_t width;
  uint32_t height;
} BsClip;

/**
 * What the shell needs from the config the moment it starts: the two hotkeys to register
 * and whether to be a login item.
 *
 * Named for when it is read, not for what it holds — [`bs_settings_list`] is the settings
 * surface, and two entry points called `bs_settings` with opposite lifetimes would be a
 * trap. A plain value struct: nothing here to free.
 */
typedef struct {
  /**
   * Carbon virtual key code, e.g. `kVK_Space`.
   */
  uint32_t hotkey_key_code;
  /**
   * Carbon modifier mask — `cmdKey`, `shiftKey` and friends, not `NSEvent` flags.
   */
  uint32_t hotkey_modifiers;
  /**
   * False if config.toml's hotkey did not parse and the default is in use.
   */
  bool hotkey_from_config;
  /**
   * A second hotkey that opens straight into the agent. Zero when none is configured —
   * key code 0 is `kVK_ANSI_A`, which is never a hotkey on its own.
   */
  uint32_t agent_hotkey_key_code;
  uint32_t agent_hotkey_modifiers;
  bool launch_at_login;
  /**
   * Whether to poll the pasteboard at all. Off means nothing is recorded.
   */
  bool clips_enabled;
  /**
   * Whether to record image clips. Off means text only.
   */
  bool clips_images;
  /**
   * Whether to read the text in an image. Only the shell can: Vision is AppKit-side.
   */
  bool clips_ocr;
} BsStartup;

/**
 * One row of the settings window: what it is, what it holds, and where that came from.
 *
 * Read-only diagnostics ride this same struct rather than earning their own — a
 * diagnostic is a setting with [`BS_SETTING_READONLY`] for a kind — so the shell has one
 * row renderer and this module one free function.
 */
typedef struct {
  /**
   * The dotted key, e.g. `agent.model`. Stable, and what every setter takes.
   */
  const uint8_t *key;
  size_t key_len;
  /**
   * The page this belongs on, as its name — "General", "Agent". A string rather than a
   * tag because the shell draws it; a numbering both sides had to agree on would be a
   * constant table for nothing.
   */
  const uint8_t *section;
  size_t section_len;
  const uint8_t *label;
  size_t label_len;
  /**
   * One line, drawn under the control.
   */
  const uint8_t *help;
  size_t help_len;
  /**
   * The value in force. Scalars are in their canonical text form — `true`, `8`,
   * `cmd+shift+space`; a [`BS_SETTING_PATHS`] value is its members separated by NUL,
   * which is the one byte a POSIX pathname cannot contain.
   */
  const uint8_t *value;
  size_t value_len;
  /**
   * What this would be with the override removed — which is what resetting restores,
   * and not necessarily the built-in default.
   */
  const uint8_t *fallback;
  size_t fallback_len;
  /**
   * One of the `BS_SETTING_*` constants.
   */
  uint8_t kind;
  /**
   * One of the `BS_SOURCE_*` constants.
   */
  uint8_t source;
  /**
   * False means the change needs a restart, which the row says.
   */
  bool live;
  /**
   * What a stepper clamps to. Both zero for a kind that has no bounds.
   */
  double min;
  double max;
} BsSetting;

/**
 * A pointer and a length, as [`BsResults`] is. Must be passed to [`bs_free_settings`].
 */
typedef struct {
  BsSetting *items;
  size_t len;
} BsSettingList;



#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Loads the config, scans for applications, and returns a handle.
 *
 * The initial scan is synchronous so that the very first query after launch sees a
 * populated index rather than an empty one — at M2 this happens before the hotkey is
 * even registered, so it costs the user nothing.
 *
 * `config_path` may be NULL, meaning `~/.config/blindspot/config.toml`. A config that
 * cannot be read or parsed falls back to defaults and complains on stderr rather than
 * failing: a typo in a TOML file must not cost the user their launcher. Returns NULL
 * only if initialisation panicked.
 *
 * # Safety
 *
 * `config_path` must be NULL or a valid NUL-terminated C string that stays alive for
 * the duration of the call. The returned pointer must eventually be passed to
 * [`bs_shutdown`], and to nothing else.
 */
BsHandle *bs_init(const char *config_path);

/**
 * Ranked matches for `query`, best first, at most `limit` of them.
 *
 * An empty query is the welcome screen: suggested apps and recent files under
 * [`BS_KIND_HEADER`] rows, with `pending` set while the recent list refreshes. A NULL
 * query is treated as an empty one; a NULL handle yields an empty result set rather
 * than a crash. A `limit` of zero yields no results; ask [`bs_max_results`] for the
 * configured cap.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut
 * down. `query` must be NULL or a valid NUL-terminated C string alive for the call.
 * The returned [`BsResults`] must be passed to [`bs_free_results`] exactly once.
 */
BsResults bs_query(BsHandle *handle, const char *query, size_t limit);

/**
 * Cancels transient searches when the panel closes.
 *
 * # Safety
 * `handle` must be NULL or a live pointer from `bs_init`.
 */
void bs_search_cancel(BsHandle *handle);

/**
 * Queues a coalesced content reconciliation without waiting for disk work.
 * # Safety
 * `handle` must be NULL or a live pointer from `bs_init` retained for this call.
 */
void bs_content_refresh(BsHandle *handle);

/**
 * Reconciles affected configured roots; invalid or oversized input requests a full scan.
 * # Safety
 * `handle` must be live and retained. `paths` must point to `len` readable bytes when non-NULL.
 */
void bs_content_refresh_paths(BsHandle *handle, const uint8_t *paths, size_t len);

/**
 * Applies the shell's power/thermal policy without waiting for the index worker.
 * # Safety
 * `handle` must be NULL or a live pointer from `bs_init` retained for this call.
 */
void bs_content_pause(BsHandle *handle, bool paused, uint8_t reason);

/**
 * Erases indexed content after explicit confirmation and disabling indexing.
 * Returns an empty blob when queued, otherwise a refusal; free with `bs_free_blob`.
 * # Safety
 * `handle` must be NULL or a live pointer retained for this call.
 */
BsBlob bs_content_erase(BsHandle *handle, bool confirmed);

/**
 * Stops erasure between transactions; already removed records stay removed.
 * # Safety
 * `handle` must be NULL or a live pointer retained for this call.
 */
void bs_content_erase_cancel(BsHandle *handle);

/**
 * Returns bounded JSON configuration/status; free it with `bs_free_blob`.
 * # Safety
 * `handle` must be NULL or a live pointer from `bs_init` retained for this call.
 */
BsBlob bs_content_state(BsHandle *handle);

/**
 * Checks an FSEvents path against the configured scope without accessing the filesystem.
 * # Safety
 * `handle` must be NULL or a live retained handle; `path` must be NULL or a valid terminated string.
 */
bool bs_content_event_relevant(BsHandle *handle,
                               const char *path);

/**
 * Runs a `:link` / `:snippet` / `:unlink` / `:unsnippet` command. Returns an empty blob on success
 * or the reason it was refused; free it with `bs_free_blob`.
 * # Safety
 * `handle` must be NULL or a live pointer from `bs_init`; `command` must be NULL or NUL-terminated.
 */
BsBlob bs_shortcut_apply(BsHandle *handle, const char *command);

/**
 * Saves `len` bytes of UTF-8 `text` as snippet `keyword`. Returns an empty blob on success or the
 * reason it was refused; free it with `bs_free_blob`.
 * # Safety
 * `handle` must be NULL or live; `keyword` NULL or NUL-terminated; `text` NULL or valid for `len` bytes.
 */
BsBlob bs_snippet_save(BsHandle *handle,
                       const char *keyword,
                       const uint8_t *text,
                       size_t len);

/**
 * The instruction for the AI command `text` names (`fix grammar`, or `ai KEYWORD` for a saved one),
 * or an empty blob when it names none; free it with `bs_free_blob`.
 * # Safety
 * `handle` must be NULL or a live pointer from `bs_init`; `text` must be NULL or NUL-terminated.
 */
BsBlob bs_prompt_resolve(BsHandle *handle, const char *text);

/**
 * Starts a user-confirmed compaction of the content index. Returns an empty blob when it started or
 * the reason it could not; free it with `bs_free_blob`.
 * # Safety
 * `handle` must be NULL or a live pointer from `bs_init`.
 */
BsBlob bs_content_compact(BsHandle *handle);

/**
 * Asks the local model what to do about `request`, on a background thread.
 *
 * Returns immediately. The answer arrives through [`bs_query`] on the same `>` request, whose
 * `pending` flag stays true until the model is done.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`]. `request` must be NULL or a valid
 * NUL-terminated C string alive for the call.
 */
void bs_agent_submit(BsHandle *handle, const char *request);

/**
 * Submits a request with ephemeral selected text, only after an explicit user action.
 *
 * # Safety
 * `handle` must be NULL or live; strings must be NULL or NUL-terminated and live for this call.
 */
void bs_agent_submit_context(BsHandle *handle, const char *request, const char *selected);

/**
 * Runs the commands the agent proposed, in order, on a background thread.
 *
 * Does nothing unless a plan is waiting and every command in it passed the refusal rules.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`].
 */
void bs_agent_run(BsHandle *handle);

/**
 * Stops whatever the agent is doing: a generation mid-stream, or a running command.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`].
 */
void bs_agent_cancel(BsHandle *handle);

/**
 * Offers the models Ollama has installed, as rows the shell shows in place of the results.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`].
 */
void bs_agent_models(BsHandle *handle);

/**
 * Picks the model at row `index` from the list [`bs_agent_models`] produced. Index 0 is
 * "Automatic", which restores the configured defaults. Remembered across restarts.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`].
 */
void bs_agent_choose(BsHandle *handle, size_t index);

/**
 * Stops waiting on the command in flight and leaves it running.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`].
 */
void bs_agent_detach(BsHandle *handle);

/**
 * Records that the user launched `result_id`.
 *
 * Updates the in-memory frecency score immediately and persists it on a detached
 * thread, so this returns without waiting on an fsync. Later queries rank a
 * frequently-launched app above an equally-good textual match.
 *
 * An id that matches nothing is recorded anyway and simply never scores against a
 * result — ids are hashes of bundle paths, so a stale one belongs to an app that has
 * been uninstalled and may yet come back.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
void bs_activate(BsHandle *handle, uint64_t result_id);

/**
 * Kicks off a rescan and returns immediately.
 *
 * The walk runs on a detached thread and swaps the new list in when it finishes, so the
 * panel can call this on every show without a keystroke ever waiting on the filesystem.
 * Concurrent calls collapse into one walk.
 *
 * Rate limited: at most one walk every 10 seconds, however often this is called. A
 * newly installed application can therefore take that long to appear.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
void bs_reindex(BsHandle *handle);

/**
 * The configured `max_results`, or 0 for a NULL handle.
 *
 * Beyond the surface sketched in CLAUDE.md, and deliberately: without it the Swift
 * side has to hardcode a row count, which makes `max_results` in the config file a
 * lie. One getter is cheaper than that inconsistency.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
size_t bs_max_results(const BsHandle *handle);

/**
 * Records a clip copied by the user.
 *
 * Swift has already refused anything carrying a privacy marker; this applies the size
 * caps, dedups against history, evicts what no longer fits, and persists. Safe to call
 * off the main thread — only brief in-memory sections are locked, never the disk write.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`]. `clip` must be NULL or point
 * to a valid [`BsClip`] whose `content` and `thumbnail` are each NULL or valid for their
 * stated lengths, for the duration of this call.
 */
void bs_clip_add(BsHandle *handle, const BsClip *clip);

/**
 * The full bytes of a clip, or its thumbnail. Empty if `id` is not a clip.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`]. The returned [`BsBlob`] must
 * be passed to [`bs_free_blob`] exactly once.
 */
BsBlob bs_clip_content(BsHandle *handle, uint64_t id, uint8_t part);

/**
 * Forgets every clip, returning how many went.
 *
 * Its own entry point rather than a settings row: "clear history now" has no value, no
 * default and nowhere for a provenance to come from. Clipboard history is its own file,
 * so this cannot touch launch history.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
uint32_t bs_clips_clear(BsHandle *handle);

/**
 * Removes one clipboard item and all stored representations.
 *
 * # Safety
 * `handle` must be null or a live handle retained until this call returns. Thread-safe.
 */
bool bs_clip_remove(BsHandle *handle, uint64_t id);

/**
 * Reads pin state without accessing disk.
 * # Safety
 * The handle is null or retained and live for this call.
 */
bool bs_clip_pinned(BsHandle *handle, uint64_t id);

/**
 * Writes pin state. Call off the UI thread.
 * # Safety
 * The handle is null or retained and live for this call.
 */
bool bs_clip_pin(BsHandle *handle, uint64_t id, bool pinned);

/**
 * Clears history, distinguishing failure from an already empty history. Call off the UI thread.
 * # Safety
 * The handle is null or retained and live for this call.
 */
bool bs_clips_clear_checked(BsHandle *handle);

/**
 * Updates a clipboard item's recency without recording application launch history.
 *
 * # Safety
 * `handle` must be null or a live handle retained until this call returns. Thread-safe.
 */
bool bs_clip_touch(BsHandle *handle, uint64_t id);

/**
 * Asks, on a thread, whether the agent's host answers.
 *
 * Returns immediately; the answer shows up in the next [`bs_settings_list`], exactly as
 * the model picker's list does. Deliberately not a synchronous getter: with Ollama
 * stopped, opening the settings window would then hang for a connect timeout.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
void bs_diagnostics_refresh(BsHandle *handle);

/**
 * Legacy PID-only signaling is unavailable; use bs_process_signal with a start time.
 *
 * # Safety
 * Takes no pointers and always returns false, preserving the old ABI without signaling.
 */
bool bs_port_kill(uint32_t pid);

/**
 * Signals only the same process instance shown in the result. Requires UI confirmation.
 */
bool bs_process_signal(uint32_t pid, uint64_t started, bool force);

/**
 * Returns JSON for a still-current process; empty means unavailable. Free with bs_free_blob.
 */
BsBlob bs_process_inspect(uint32_t pid, uint64_t started);

/**
 * Spells a Carbon key code and modifier mask the way config.toml writes it.
 *
 * The settings window's recorder turns an `NSEvent` into a code and a mask — genuinely
 * shell-side work, since Carbon and AppKit modifier bits share no positions — and this
 * turns that back into the one canonical string. The chord vocabulary therefore lives in
 * exactly one place, and `hotkey::format`'s round-trip test is what keeps it honest.
 *
 * An empty blob means the key has no name blindspot could write into a config file.
 *
 * # Safety
 *
 * The returned [`BsBlob`] must be passed to [`bs_free_blob`] exactly once.
 */
BsBlob bs_hotkey_format(uint32_t key_code, uint32_t modifiers);

/**
 * Releases a [`BsBlob`].
 *
 * # Safety
 *
 * `blob` must be exactly what [`bs_clip_content`] returned, freed at most once.
 */
void bs_free_blob(BsBlob blob);

/**
 * The two hotkeys and the login-item flag, read from the config in force.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 * A NULL handle yields the defaults.
 */
BsStartup bs_startup(const BsHandle *handle);

/**
 * Every settable knob and every diagnostic, in the order the window draws them.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 * The returned [`BsSettingList`] must be passed to [`bs_free_settings`] exactly once.
 */
BsSettingList bs_settings_list(const BsHandle *handle);

/**
 * Releases everything a [`bs_settings_list`] result owns.
 *
 * # Safety
 *
 * `list` must be exactly what [`bs_settings_list`] returned, not modified since, and
 * freed at most once.
 */
void bs_free_settings(BsSettingList list);

/**
 * Records `key` as set to `value` and applies it.
 *
 * Returns the reason it was refused, or an empty blob on success — so the window can say
 * *why* a chord or a host was rejected, which a boolean could not. The value is written
 * to the overrides file; **config.toml is never touched**.
 *
 * `value` is pointer + length rather than a C string because a [`BS_SETTING_PATHS`] value
 * separates its members with NUL.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`]. `key` must be NULL or a valid
 * NUL-terminated C string alive for the call, and `value` NULL or valid for `value_len`
 * bytes. The returned [`BsBlob`] must be passed to [`bs_free_blob`] exactly once.
 */
BsBlob bs_setting_set(BsHandle *handle, const char *key, const uint8_t *value, size_t value_len);

/**
 * Forgets whatever the window set for `key`, so it falls back to config.toml and then to
 * the built-in default. Returns a refusal the same way [`bs_setting_set`] does.
 *
 * # Safety
 *
 * As [`bs_setting_set`].
 */
BsBlob bs_setting_reset(BsHandle *handle, const char *key);

/**
 * Releases everything a [`bs_query`] result owns.
 *
 * # Safety
 *
 * `results` must be exactly what a [`bs_query`] call returned, not modified since,
 * and freed at most once. Passing a zeroed or hand-built struct is undefined.
 */
void bs_free_results(BsResults results);

/**
 * Destroys the handle.
 *
 * A rescan thread may still be walking; it holds `Arc` clones of everything it needs,
 * so it finishes harmlessly and drops the index afterwards.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`], shut down at most once,
 * with no other call on it in flight or afterwards.
 */
void bs_shutdown(BsHandle *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BLINDSPOT_H */
