#ifndef BLINDSPOT_H
#define BLINDSPOT_H

/* Generated by cbindgen. Edit core/src/ffi.rs and run `make header`; do not edit this file. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque to C. Swift only ever holds a `BsHandle *`.
 */
typedef struct BsHandle BsHandle;

/**
 * One ranked match.
 *
 * `name` and `path` are pointer + length, not NUL-terminated: a bundle path is bytes
 * on macOS, not necessarily valid UTF-8, and a length keeps that honest. Swift reads
 * them with `String(decoding:as:)` over an `UnsafeRawBufferPointer`.
 *
 * `path` is in the struct because Swift needs it twice — once for
 * `NSWorkspace.icon(forFile:)` and once to launch — and re-deriving it from `id` would
 * mean a second FFI call per row per keystroke.
 */
typedef struct {
  uint64_t id;
  const uint8_t *name;
  size_t name_len;
  const uint8_t *path;
  size_t path_len;
  uint32_t score;
} BsResult;

/**
 * A pointer and a length, so one query is one struct rather than a Swift-side array
 * copy per keystroke. Must be passed to [`bs_free_results`] on every path.
 */
typedef struct {
  BsResult *items;
  size_t len;
} BsResults;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Loads the config, scans for applications, and returns a handle.
 *
 * The initial scan is synchronous so that the very first query after launch sees a
 * populated index rather than an empty one — at M2 this happens before the hotkey is
 * even registered, so it costs the user nothing.
 *
 * `config_path` may be NULL, meaning `~/.config/blindspot/config.toml`. A config that
 * cannot be read or parsed falls back to defaults and complains on stderr rather than
 * failing: a typo in a TOML file must not cost the user their launcher. Returns NULL
 * only if initialisation panicked.
 *
 * # Safety
 *
 * `config_path` must be NULL or a valid NUL-terminated C string that stays alive for
 * the duration of the call. The returned pointer must eventually be passed to
 * [`bs_shutdown`], and to nothing else.
 */
BsHandle *bs_init(const char *config_path);

/**
 * Ranked matches for `query`, best first, at most `limit` of them.
 *
 * A NULL handle or a NULL query yields an empty result set rather than a crash. A
 * `limit` of zero yields no results; ask [`bs_max_results`] for the configured cap.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut
 * down. `query` must be NULL or a valid NUL-terminated C string alive for the call.
 * The returned [`BsResults`] must be passed to [`bs_free_results`] exactly once.
 */
BsResults bs_query(BsHandle *handle, const char *query, size_t limit);

/**
 * Records that the user launched `result_id`.
 *
 * A no-op at M1. It exists now so that M3's frecency store is a pure-Rust change with
 * no header regeneration and no Swift edit — the call site is already in place and
 * already passing the stable id it will need.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
void bs_activate(BsHandle *handle, uint64_t result_id);

/**
 * Kicks off a rescan and returns immediately.
 *
 * The walk runs on a detached thread and swaps the new list in when it finishes, so the
 * panel can call this on every show without a keystroke ever waiting on the filesystem.
 * Concurrent calls collapse into one walk.
 *
 * Rate limited: at most one walk every 10 seconds, however often this is called. A
 * newly installed application can therefore take that long to appear.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
void bs_reindex(BsHandle *handle);

/**
 * The configured `max_results`, or 0 for a NULL handle.
 *
 * Beyond the surface sketched in CLAUDE.md, and deliberately: without it the Swift
 * side has to hardcode a row count, which makes `max_results` in the config file a
 * lie. One getter is cheaper than that inconsistency.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
size_t bs_max_results(const BsHandle *handle);

/**
 * Releases everything a [`bs_query`] result owns.
 *
 * # Safety
 *
 * `results` must be exactly what a [`bs_query`] call returned, not modified since,
 * and freed at most once. Passing a zeroed or hand-built struct is undefined.
 */
void bs_free_results(BsResults results);

/**
 * Destroys the handle.
 *
 * A rescan thread may still be walking; it holds `Arc` clones of everything it needs,
 * so it finishes harmlessly and drops the index afterwards.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`], shut down at most once,
 * with no other call on it in flight or afterwards.
 */
void bs_shutdown(BsHandle *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BLINDSPOT_H */
