#ifndef BLINDSPOT_H
#define BLINDSPOT_H

/* Generated by cbindgen. Edit core/src/ffi.rs and run `make header`; do not edit this file. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A query beginning with this searches clipboard history instead of the app index.
 */
#define PREFIX ';'

/**
 * A [`BsResult`] that is an application bundle.
 */
#define BS_KIND_APP 0

/**
 * A [`BsResult`] that is a file found through Spotlight.
 */
#define BS_KIND_FILE 1

/**
 * A [`BsResult`] that is a calculator answer. Its `path` is empty — there is nothing to
 * open — and `name` is the formatted result, which Swift copies on Enter.
 */
#define BS_KIND_CALC 2

/**
 * A [`BsResult`] that is a text clip from clipboard history.
 */
#define BS_KIND_CLIP_TEXT 3

/**
 * A [`BsResult`] that is an image clip from clipboard history.
 */
#define BS_KIND_CLIP_IMAGE 4

/**
 * `part` for [`bs_clip_content`]: the full text, or the full PNG.
 */
#define BS_CLIP_FULL 0

/**
 * `part` for [`bs_clip_content`]: the row thumbnail. Empty for text clips.
 */
#define BS_CLIP_THUMBNAIL 1

/**
 * Opaque to C. Swift only ever holds a `BsHandle *`.
 */
typedef struct BsHandle BsHandle;

/**
 * One ranked match.
 *
 * `name` and `path` are pointer + length, not NUL-terminated: a bundle path is bytes
 * on macOS, not necessarily valid UTF-8, and a length keeps that honest. Swift reads
 * them with `String(decoding:as:)` over an `UnsafeRawBufferPointer`.
 *
 * `path` is in the struct because Swift needs it twice — once for
 * `NSWorkspace.icon(forFile:)` and once to launch — and re-deriving it from `id` would
 * mean a second FFI call per row per keystroke.
 */
typedef struct {
  uint64_t id;
  const uint8_t *name;
  size_t name_len;
  const uint8_t *path;
  size_t path_len;
  uint32_t score;
  /**
   * One of the `BS_KIND_*` constants. Swift needs it to decide what Enter does.
   */
  uint8_t kind;
  /**
   * Unix seconds a clip was last copied, so Swift can show "2 min ago" with its own
   * localized formatter. Zero for anything that is not a clip.
   */
  uint64_t timestamp;
  /**
   * Pixel size of an image clip, zero otherwise. Swift compares it against the
   * attached displays to call a full-screen capture a screenshot.
   */
  uint32_t width;
  uint32_t height;
} BsResult;

/**
 * A pointer and a length, so one query is one struct rather than a Swift-side array
 * copy per keystroke. Must be passed to [`bs_free_results`] on every path.
 */
typedef struct {
  BsResult *items;
  size_t len;
  /**
   * True while a file search for this query is still running, meaning more results
   * may follow. Swift polls until it goes false. Always false for a query with no
   * `?` prefix, because nothing asynchronous was started.
   */
  bool pending;
} BsResults;

/**
 * A clip handed from Swift to Rust. Every pointer only has to live for the call:
 * [`bs_clip_add`] copies whatever it keeps before returning.
 */
typedef struct {
  /**
   * [`BS_KIND_CLIP_TEXT`] or [`BS_KIND_CLIP_IMAGE`].
   */
  uint8_t kind;
  /**
   * UTF-8 text, or PNG bytes.
   */
  const uint8_t *content;
  size_t content_len;
  /**
   * A small PNG for the row. May be NULL for text.
   */
  const uint8_t *thumbnail;
  size_t thumbnail_len;
  /**
   * For images, UTF-8 text recognised in the image, which becomes its name and makes it
   * searchable. May be NULL. Ignored for text clips.
   */
  const uint8_t *text;
  size_t text_len;
  uint32_t width;
  uint32_t height;
} BsClip;

/**
 * Bytes owned by Rust. Must be passed to [`bs_free_blob`].
 */
typedef struct {
  const uint8_t *data;
  size_t len;
} BsBlob;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Loads the config, scans for applications, and returns a handle.
 *
 * The initial scan is synchronous so that the very first query after launch sees a
 * populated index rather than an empty one — at M2 this happens before the hotkey is
 * even registered, so it costs the user nothing.
 *
 * `config_path` may be NULL, meaning `~/.config/blindspot/config.toml`. A config that
 * cannot be read or parsed falls back to defaults and complains on stderr rather than
 * failing: a typo in a TOML file must not cost the user their launcher. Returns NULL
 * only if initialisation panicked.
 *
 * # Safety
 *
 * `config_path` must be NULL or a valid NUL-terminated C string that stays alive for
 * the duration of the call. The returned pointer must eventually be passed to
 * [`bs_shutdown`], and to nothing else.
 */
BsHandle *bs_init(const char *config_path);

/**
 * Ranked matches for `query`, best first, at most `limit` of them.
 *
 * A NULL handle or a NULL query yields an empty result set rather than a crash. A
 * `limit` of zero yields no results; ask [`bs_max_results`] for the configured cap.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut
 * down. `query` must be NULL or a valid NUL-terminated C string alive for the call.
 * The returned [`BsResults`] must be passed to [`bs_free_results`] exactly once.
 */
BsResults bs_query(BsHandle *handle, const char *query, size_t limit);

/**
 * Records that the user launched `result_id`.
 *
 * Updates the in-memory frecency score immediately and persists it on a detached
 * thread, so this returns without waiting on an fsync. Later queries rank a
 * frequently-launched app above an equally-good textual match.
 *
 * An id that matches nothing is recorded anyway and simply never scores against a
 * result — ids are hashes of bundle paths, so a stale one belongs to an app that has
 * been uninstalled and may yet come back.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
void bs_activate(BsHandle *handle, uint64_t result_id);

/**
 * Kicks off a rescan and returns immediately.
 *
 * The walk runs on a detached thread and swaps the new list in when it finishes, so the
 * panel can call this on every show without a keystroke ever waiting on the filesystem.
 * Concurrent calls collapse into one walk.
 *
 * Rate limited: at most one walk every 10 seconds, however often this is called. A
 * newly installed application can therefore take that long to appear.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
void bs_reindex(BsHandle *handle);

/**
 * The configured `max_results`, or 0 for a NULL handle.
 *
 * Beyond the surface sketched in CLAUDE.md, and deliberately: without it the Swift
 * side has to hardcode a row count, which makes `max_results` in the config file a
 * lie. One getter is cheaper than that inconsistency.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`] that has not been shut down.
 */
size_t bs_max_results(const BsHandle *handle);

/**
 * Records a clip copied by the user.
 *
 * Swift has already refused anything carrying a privacy marker; this applies the size
 * caps, dedups against history, evicts what no longer fits, and persists. Safe to call
 * off the main thread — only brief in-memory sections are locked, never the disk write.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`]. `clip` must be NULL or point
 * to a valid [`BsClip`] whose `content` and `thumbnail` are each NULL or valid for their
 * stated lengths, for the duration of this call.
 */
void bs_clip_add(BsHandle *handle, const BsClip *clip);

/**
 * The full bytes of a clip, or its thumbnail. Empty if `id` is not a clip.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`]. The returned [`BsBlob`] must
 * be passed to [`bs_free_blob`] exactly once.
 */
BsBlob bs_clip_content(BsHandle *handle, uint64_t id, uint8_t part);

/**
 * Releases a [`BsBlob`].
 *
 * # Safety
 *
 * `blob` must be exactly what [`bs_clip_content`] returned, freed at most once.
 */
void bs_free_blob(BsBlob blob);

/**
 * Releases everything a [`bs_query`] result owns.
 *
 * # Safety
 *
 * `results` must be exactly what a [`bs_query`] call returned, not modified since,
 * and freed at most once. Passing a zeroed or hand-built struct is undefined.
 */
void bs_free_results(BsResults results);

/**
 * Destroys the handle.
 *
 * A rescan thread may still be walking; it holds `Arc` clones of everything it needs,
 * so it finishes harmlessly and drops the index afterwards.
 *
 * # Safety
 *
 * `handle` must be NULL or a live pointer from [`bs_init`], shut down at most once,
 * with no other call on it in flight or afterwards.
 */
void bs_shutdown(BsHandle *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BLINDSPOT_H */
